//Generated by tools/genarenas.py - do not edit by hand.

#ifndef ARENAS_H
#define ARENAS_H

extern const unsigned short siloGirderMap[1024];
extern const unsigned short templeGirderMap[1024];
extern const unsigned short blankMap[1024];

#endif
