//Generated by tools/genskins.py - do not edit by hand.

#ifndef PLAYERSKINS_H
#define PLAYERSKINS_H

#define PLAYER_SKIN_FRAMES 14
#define PLAYER_SKIN_EXTRA  7
#define playerSkinTilesLen 6272

extern const unsigned short playerSkinTiles[3136];

#endif
