#!/usr/bin/env python3
"""Generate arena tilemaps for SuperCrateBox-GBA.

Layouts are authored as a grid of characters and turned into girder-layer tile
indices here, so platform end caps and ladder junctions are worked out rather
than hand-counted. The girder layer doubles as the collision map, so the tile
conventions matter: 16-20 are deadly, 21-25 are passable, 0 is open air and
everything else is solid.

Emits arenas.c / arenas.h.  Usage: tools/genarenas.py <outdir>
"""
import sys

W, H = 30, 20                 # visible tiles; the screenblock is 32x32
AIR, WALL, CORNER = 0, 1, 2
PLAT, PLAT_R, PLAT_L, PLAT_LADDER = 3, 4, 5, 6
BRICK = [7, 8, 7, 8, 7, 8, 7, 9]
GROUND = [11, 12, 13, 11, 13, 11, 12, 13, 12, 11]
FIRE = 16
LADDER = 21

def grid():
    g = [['.'] * W for _ in range(H)]
    for r in range(H - 1):
        g[r][0] = '|'
        g[r][W - 1] = '|'
    return g

def platform(g, r, c0, c1):
    for c in range(c0, c1 + 1):
        g[r][c] = '='

def ladder(g, c, r0, r1):
    for r in range(r0, r1 + 1):
        g[r][c] = 'H'

def ceiling(g):
    platform(g, 0, 1, 13)
    platform(g, 0, 16, W - 2)
    g[0][0] = '+'
    g[0][W - 1] = '+'

def floor(g, brick_left, brick_right):
    for c in range(W):
        g[H - 1][c] = 'g'
    g[H - 1][14] = 'F'
    g[H - 1][15] = 'F'
    for c in range(0, brick_left + 1):
        g[H - 2][c] = 'b'
    for c in range(brick_right, W):
        g[H - 2][c] = 'b'

def to_tiles(g):
    """Character grid -> 32x32 tile indices."""
    out = [[0] * 32 for _ in range(32)]
    for r in range(H):
        for c in range(W):
            ch = g[r][c]
            if ch == '.':
                t = AIR
            elif ch == '|':
                t = WALL
            elif ch == '+':
                t = CORNER
            elif ch == 'H':
                t = LADDER
            elif ch == 'F':
                t = FIRE
            elif ch == 'b':
                t = BRICK[c % len(BRICK)]
            elif ch == 'g':
                t = GROUND[c % len(GROUND)]
            elif ch == '=':
                # a ladder passing through a platform gets the junction tile
                above = g[r - 1][c] if r > 0 else '.'
                below = g[r + 1][c] if r < H - 1 else '.'
                if above == 'H' or below == 'H':
                    t = PLAT_LADDER
                else:
                    left = g[r][c - 1] if c > 0 else '.'
                    right = g[r][c + 1] if c < W - 1 else '.'
                    if left != '=':
                        t = PLAT_L
                    elif right != '=':
                        t = PLAT_R
                    else:
                        t = PLAT
            else:
                raise ValueError("unknown layout character %r" % ch)
            out[r][c] = t
    return out

# ---------------------------------------------------------------- layouts

def rocket_silo():
    """Narrow side ledges around a tall central shaft."""
    g = grid()
    ceiling(g)
    platform(g, 4, 1, 10);   platform(g, 4, 19, W - 2)
    platform(g, 8, 8, 21)
    platform(g, 12, 1, 10);  platform(g, 12, 19, W - 2)
    platform(g, 16, 8, 21)
    ladder(g, 5, 1, 3);      ladder(g, 24, 1, 3)
    ladder(g, 14, 5, 7);     ladder(g, 15, 5, 7)
    ladder(g, 5, 9, 11);     ladder(g, 24, 9, 11)
    ladder(g, 10, 13, 15);   ladder(g, 19, 13, 15)
    ladder(g, 10, 17, 17);   ladder(g, 19, 17, 17)
    floor(g, 6, 23)
    return g

def moon_temple():
    """Stepped terraces, with a landing in the middle of the arena."""
    g = grid()
    ceiling(g)
    platform(g, 5, 3, 11);   platform(g, 5, 18, 26)
    platform(g, 9, 1, 7);    platform(g, 9, 12, 17);  platform(g, 9, 22, W - 2)
    platform(g, 13, 3, 11);  platform(g, 13, 18, 26)
    platform(g, 17, 10, 19)
    ladder(g, 7, 1, 4);      ladder(g, 22, 1, 4)
    ladder(g, 5, 6, 8);      ladder(g, 24, 6, 8)
    ladder(g, 14, 10, 12);   ladder(g, 15, 10, 12)
    ladder(g, 7, 14, 16);    ladder(g, 22, 14, 16)
    floor(g, 7, 22)
    return g

ARENAS = [("silo", rocket_silo), ("temple", moon_temple)]

# ---------------------------------------------------------------- output

def emit(outdir):
    body = ["//Generated by tools/genarenas.py - do not edit by hand.",
            "//Girder (collision) layers for the arenas past the first.",
            "", '#include "arenas.h"', ""]
    for name, fn in ARENAS:
        tiles = to_tiles(fn())
        body.append("const unsigned short %sGirderMap[1024] = {" % name)
        flat = [tiles[r][c] for r in range(32) for c in range(32)]
        for i in range(0, 1024, 16):
            body.append("\t" + "".join("%3d," % v for v in flat[i:i + 16]))
        body += ["};", ""]
    body.append("const unsigned short blankMap[1024] = {0};")
    body.append("")
    open(outdir + "/arenas.c", "w").write("\n".join(body))

    head = ["//Generated by tools/genarenas.py - do not edit by hand.", "",
            "#ifndef ARENAS_H", "#define ARENAS_H", ""]
    for name, _ in ARENAS:
        head.append("extern const unsigned short %sGirderMap[1024];" % name)
    head += ["extern const unsigned short blankMap[1024];", "", "#endif", ""]
    open(outdir + "/arenas.h", "w").write("\n".join(head))

def preview():
    for name, fn in ARENAS:
        g = fn()
        print("== %s ==" % name)
        for r in range(H):
            print("  " + "".join(g[r]))
        print()

if __name__ == "__main__":
    preview()
    if len(sys.argv) > 1:
        emit(sys.argv[1])
        print("wrote arenas.c / arenas.h")
